version: '3'

services:
  postgres:
    build:
      context: .db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  spring-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
